name: Publish Docker images

on:
  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io' }}
  IMAGE_NAME: ${{ github.repository }}
  TARGET_PLATFORMS: linux/amd64,linux/arm64

jobs:
  push_to_registry:
    name: Build & Push Image
    strategy:
      matrix:
        pg_major: [15, 16, 17]
        postgis_major: [3]
        pgvector_version: ['0.8.1']
        vchord_version: ['0.5.3']
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME || (env.REGISTRY == 'ghcr.io' && github.actor) }}
          password: ${{ secrets.DOCKER_PASSWORD || (env.REGISTRY == 'ghcr.io' && secrets.GITHUB_TOKEN) }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            pg${{ matrix.pg_major }}-postgis${{ matrix.postgis_major }}-pgvector${{ matrix.pgvector_version }}-vchord${{ matrix.vchord_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}
          build-args: |
            PG_MAJOR=${{ matrix.pg_major }}
            POSTGIS_MAJOR=${{ matrix.postgis_major }}
            PGVECTOR_VERSION=${{ matrix.pgvector_version }}
            VCHORD_VERSION=${{ matrix.vchord_version }}
